baseURL = "https://zhenshuo-zhang.github.io/MyBlog/"
canonifyURLs = true
languageCode = 'zh-cn'
title = '我的博客'
theme = 'simple-blog'

[params]
description = "欢迎来到我的个人博客，这里分享技术、生活和思考。"
author = "博主"
email = "your-email@example.com"
github = "https://github.com/yourusername"

[menu]
[[menu.main]]
name = "关于"
url = "/about"
weight = 10

[[menu.main]]
name = "归档"
url = "/archives"
weight = 20

[[menu.main]]
name = "标签"
url = "/tags"
weight = 30
