baseURL = "https://zhenshuo-zhang.github.io/MyBlog/"
canonifyURLs = true
languageCode = 'zh-cn'
title = '我的博客'
theme = 'simple-blog'

[params]
description = "欢迎来到我的个人博客，这里分享技术、生活和思考。"
author = "张振硕"
email = "zhenshuo.zhang@example.com"
github = "https://github.com/zhenshuo-zhang"
twitter = "https://twitter.com/yourusername"
linkedin = "https://linkedin.com/in/yourusername"

[menu]
[[menu.main]]
name = "关于"
url = "/about"
weight = 10

[[menu.main]]
name = "归档"
url = "/archives"
weight = 20

[[menu.main]]
name = "标签"
url = "/tags"
weight = 30

# 分页设置
paginate = 6
paginatePath = "page"